version: '{build}'

branches:
  only:
    - main

skip_tags: true

image: Ubuntu2204

init:
#    - sudo apt-get update
#    - sudo apt-get upgrade
    - sudo apt-get install -y python3.11 python3-pip
    - python3 -m pip install --upgrade pip
    - pip3 install scons markdown
    - sudo apt-get install -y gettext
# clone_dir: C:\projects\myprojec

install: off

build: off
#build_mode: script
build_script:
    - sh: |
        scons version={build}

test: off
deploy: off

artifacts:
    - path: '*.nvda-addon'

on_success:
    - "appveyor PushArtifact *.nvda-addon"