version: '{build}'

branches:
  only:
    - main

skip_tags: true

image: Ubuntu2204

#init:
#    - sudo apt-get update
#    - sudo apt-get upgrade


environment:
    PY_PYTHON: 3.11-32

install: 
#    - sudo apt-get install -y python3.11 python3-pip
    - sudo pip install --upgrade --no-warn-script-location pip
    - sudo pip install --no-warn-script-location scons markdown 
    - sudo apt-get install -y gettext


build: off
#build_mode: script
build_script:
    - scons version=$(printenv appveyor_build_number)

test: off
deploy: off

artifacts:
    - path: '*.nvda-addon'

on_success:
    - "appveyor PushArtifact *.nvda-addon"