name: pull_request

on:
  pull_request:
    types: [synchronize]

jobs:
  scons:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: 3.11
    - name: Install dependencies
      run: pip install scons markdown
    - name: update pckages
      run: sudo apt-get update
    - name: install gettext
      run: sudo apt-get install gettext
    - name: get commit hash
      run: echo "COMMIT_HASH=$(git rev-parse --short ${{ github.event.pull_request.head.sha }})" >> $GITHUB_ENV
    - name: build with hash of commit
      run: scons version=$COMMIT_HASH
    - name: upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: build-artifact
        path: *.nvda-addon
    - name: comment on pull request
      uses: actions/github-script@v5
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          github.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: `Addon built successfully. [Download here](${{ steps.upload-artifact.outputs.arttifact-url }})`