name: scons
on: 
  push:
    tags: 
      - '*'

jobs:
  call-workflow-passing-data:
    uses: Nael-Sayegh/github-action/.github/workflows/release.yml@main
    with:
      nameTag: ${GITHUB_REF#refs/*/}
    secrets: inherit