name: scons
on: 
  push:
    tags: 
      - '*'

jobs:
  scons: 
    runs-on: ubuntu-latest
    steps:
      - name: call reuse action
        uses: Nael-Sayegh/github-action/.github/workflows/sftp@main
        secrets: inherit